/* SPDX-License-Identifier: GPL-2.0+ */
/*
 * am62xx and j722s common LPM registers
 *
 * Copyright (C) 2026 Texas Instruments Incorporated - https://www.ti.com/
 */

#ifndef __ASM_ARCH_AM62XX_J722S_LPM_HARDWARE_H
#define __ASM_ARCH_AM62XX_J722S_LPM_HARDWARE_H

#define WKUP_CTRL_MMR_PMCTRL_IO_0						0x18084
#define WKUP_CTRL_MMR_PMCTRL_IO_1						0x18088
#define WKUP_CTRL_MMR_PMCTRL_IO_0_ISOCLK_OVRD_0			BIT(0)
#define WKUP_CTRL_MMR_PMCTRL_IO_0_ISOOVR_EXTEND_0		BIT(4)
#define WKUP_CTRL_MMR_PMCTRL_IO_0_ISO_BYPASS_OVR_0		BIT(6)
#define WKUP_CTRL_MMR_PMCTRL_IO_0_WUCLK_CTRL_0			BIT(8)
#define WKUP_CTRL_MMR_PMCTRL_IO_0_GLOBAL_WUEN_0			BIT(16)
#define WKUP_CTRL_MMR_PMCTRL_IO_0_IO_ISO_CTRL_0			BIT(24)
#define WKUP_CTRL_MMR_PMCTRL_IO_0_IO_ISO_STATUS_0		BIT(25)
#define WKUP_CTRL_MMR_PMCTRL_IO_0_WRITE_MASK ( \
		WKUP_CTRL_MMR_PMCTRL_IO_0_ISOCLK_OVRD_0 |	\
		WKUP_CTRL_MMR_PMCTRL_IO_0_ISOOVR_EXTEND_0 |	\
		WKUP_CTRL_MMR_PMCTRL_IO_0_ISO_BYPASS_OVR_0 |	\
		WKUP_CTRL_MMR_PMCTRL_IO_0_WUCLK_CTRL_0 |	\
		WKUP_CTRL_MMR_PMCTRL_IO_0_GLOBAL_WUEN_0 |	\
		WKUP_CTRL_MMR_PMCTRL_IO_0_IO_ISO_CTRL_0)

#define WKUP_CTRL_MMR_PMCTRL_IO_GLB						0x1809c
#define WKUP_CTRL_MMR_DEEPSLEEP_CTRL					0x18160

#define WKUP_CTRL_MMR_CANUART_WAKE_CTRL					0x18300
#define WKUP_CTRL_MMR_CANUART_WAKE_CTRL_MW				0x2aaaaaaa
#define WKUP_CTRL_MMR_CANUART_WAKE_CTRL_MW_SHIFT		1
#define WKUP_CTRL_MMR_CANUART_WAKE_CTRL_MW_LOAD_EN		BIT(0)

#define WKUP_CTRL_MMR_CANUART_WAKE_STAT1				0x1830c
#define WKUP_CTRL_MMR_CANUART_WAKE_STAT1_CANUART_IO_MODE	BIT(0)

#define WKUP_CTRL_MMR_CANUART_WAKE_OFF_MODE_STAT		0x18318
#define WKUP_CTRL_MMR_CANUART_WAKE_OFF_MODE_STAT_MW		0x555555

#define K3_R5_MEMREGION_LPM_METADATA_OFFSET				0x108000

#define CLKSTOP_TRANSITION_TIMEOUT_MS					10

#endif /* __ASM_ARCH_AM62XX_J722S_LPM_HARDWARE_H */
